name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION
        script: |
          # Set non-interactive frontend for package installation
          export DEBIAN_FRONTEND=noninteractive
          
          # Clean up previous deployment
          rm -rf /home/ubuntu/classroom-notes
          mkdir -p /home/ubuntu/classroom-notes
          cd /home/ubuntu/classroom-notes
          
          # Clone the repository
          git clone https://github.com/infofitsoftware/livecode_orginal.git .
          
          # Make the deployment script executable
          chmod +x scripts/deploy.sh
          
          # Run the deployment script
          ./scripts/deploy.sh 